import assert from 'node:assert/strict'
import test from 'node:test'
import { cp, mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { inspectDecisionEffectsInline, verifyDecisionEffectsInline, verifyDecisionEffects } from '../lib/decision-effect-proof.mjs'
const source = await readFile(new URL('../examples/decision-effects.json', import.meta.url), 'utf8'), fixture = () => JSON.parse(source), codes = report => report.findings.map(f => f.code)
test('verifies settled allow and denied no-effect records deterministically', () => { const a = verifyDecisionEffectsInline({ evidenceJson: source }), b = verifyDecisionEffectsInline({ evidenceJson: source }); assert.equal(a.status, 'verified'); assert.deepEqual(a.summary, { records: 2, allowed: 1, denied: 1, succeeded: 1, findings: 0 }); assert.equal(a.reportSha256, b.reportSha256); assert.equal(a.claims.authorizationIsNotExecution, true); assert.equal(a.claims.effectOccurrenceProven, false) })
test('rejects denied effects and request mismatch', () => { const v = fixture(); v.records[1].effect.status = 'failed'; v.records[1].effect.requestSha256 = 'f'.repeat(64); const r = verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(v) }); assert.ok(codes(r).includes('DENIED_ACTION_EFFECT_OBSERVED')); assert.ok(codes(r).includes('REQUEST_BINDING_MISMATCH')) })
test('rejects missing confirmation and insufficient high-risk authority', () => { const v = fixture(); v.records[0].riskClass = 'destructive'; v.records[0].requiresConfirmation = true; const r = verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(v) }); assert.ok(codes(r).includes('CONFIRMATION_MISSING')); assert.ok(codes(r).includes('HIGH_RISK_AUTHORITY_INSUFFICIENT')) })
test('rejects stale policy and state versions', () => { const v = fixture(); v.records[0].policyRevisionSha256 = 'a'.repeat(64); v.records[0].effect.stateBeforeSha256 = 'b'.repeat(64); const r = verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(v) }); assert.ok(codes(r).includes('POLICY_REVISION_MISMATCH')); assert.ok(codes(r).includes('STATE_VERSION_MISMATCH')) })
test('rejects missing effects for required allows and unresolved effects', () => { const a = fixture(); a.records[0].effect.status = 'not-attempted'; a.records[0].effect.stateAfterSha256 = a.records[0].effect.stateBeforeSha256; assert.ok(codes(verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(a) })).includes('AUTHORIZED_NOT_EXECUTED')); const b = fixture(); b.records[0].effect.status = 'unknown'; assert.ok(codes(verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(b) })).includes('EFFECT_UNRESOLVED')) })
test('detects replay, duplicates and ordering faults', () => { const v = fixture(); v.records[1].decisionId = v.records[0].decisionId; v.records[1].idempotencySha256 = v.records[0].idempotencySha256; v.records[1].effect.effectId = v.records[0].effect.effectId; v.records[1].sequence = 5; const c = codes(verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(v) })); for (const expected of ['DUPLICATE_DECISION', 'IDEMPOTENCY_REPLAY', 'DUPLICATE_EFFECT', 'DECISION_ORDER_INVALID']) assert.ok(c.includes(expected)) })
test('rejects secret-shaped and raw business fields', () => { const v = fixture(); v.records[0].payload = 'private'; assert.throws(() => verifyDecisionEffectsInline({ evidenceJson: JSON.stringify(v) }), e => e.code === 'FORBIDDEN_FIELD') })
test('inspection is body-free and non-executing', () => { const r = inspectDecisionEffectsInline({ evidenceJson: source }); assert.equal(r.records, 2); assert.equal(r.readsBusinessBodies, false); assert.equal(r.executesActions, false); assert.equal(r.signsAuthority, false) })
test('publishes replay-safe content-addressed artifact with read-back proof', async () => { const root = await mkdtemp(path.join(tmpdir(), 'dsh-decision-effect-')); try { await cp(new URL('../examples/', import.meta.url), root, { recursive: true }); const a = await verifyDecisionEffects({ workspaceRoot: root, evidencePath: 'decision-effects.json', artifactDir: 'artifacts' }), b = await verifyDecisionEffects({ workspaceRoot: root, evidencePath: 'decision-effects.json', artifactDir: 'artifacts' }); assert.equal(a.status, 'verified'); assert.equal(a.artifact.path, b.artifact.path); assert.equal(a.artifact.verifiedByReadBack, true) } finally { await rm(root, { recursive: true, force: true }) } })
test('rejects workspace traversal', async () => { const root = await mkdtemp(path.join(tmpdir(), 'dsh-decision-effect-')); try { await assert.rejects(verifyDecisionEffects({ workspaceRoot: root, evidencePath: '../outside.json', artifactDir: 'artifacts' }), e => e.code === 'UNSAFE_PATH') } finally { await rm(root, { recursive: true, force: true }) } })
